<?php

/**
 * chart.module : Flukso chart rendering using the Highstock js charting lib
 * 
 * Copyright (c) 2011 Bart Van Der Meerssche <bart.vandermeerssche@flukso.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

define('CHART_PATH', drupal_get_path('module', 'chart'));

/**
 * hook_menu() callback 
 */
function chart_menu() {
  $items = array();

  $items['chart'] = array(
    'title'               => 'your charts',
    'description'         => 'Render Flukso time series charts.',
    'page callback'       => '_chart_render',
    'page arguments'      => array('electricity', 'day'),
    'access callback'     => TRUE,
    'type'                => MENU_CALLBACK,
  );

  return $items;
} 

function _chart_render() {
  global $user;

  drupal_add_js(CHART_PATH . '/js/highstock.src.js');
  drupal_add_js(CHART_PATH . '/js/flukso.js');

  drupal_add_js(array('uid' => $user->uid) , 'setting');

  $output .= '<ul class="tabs primary">';
  $output .= '<li id="electricity" class="active"><a href="/chart" class="active">electricity</a></li>';
  $output .= '<li id="gas"><a href="/chart">gas</a></li>';
  $output .= '<li id="water"><a href="/chart">water</a></li>';
  $output .= '</ul>';

  $output .= '<ul class="tabs secondary">';
  $output .= '<li id="hour"><a href="/chart">hour</a></li>';
  $output .= '<li id="day" class="active" ><a href="/chart" class="active">day</a></li>';
  $output .= '<li id="month"><a href="/chart">month</a></li>';
  $output .= '<li id="year"><a href="/chart">year</a></li>';
  $output .= '<li id="night"><a href="/chart">night</a></li>';
  $output .= '</ul>';

  $output .= '<div id="chart" style="height: 500px; width: 600px; margin: 1.5em 0 0 0;"></div>';

  return $output;
}
