<?php

/**
 * chart.module : Flukso chart rendering using the Highstock js charting lib
 * 
 * Copyright (c) 2011 Bart Van Der Meerssche <bart.vandermeerssche@flukso.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

define('CHART_PATH', drupal_get_path('module', 'chart'));

/**
 * hook_menu() callback 
 */
function chart_menu() {
  $items = array();

  $items['chart'] = array(
    'title'               => 'your charts',
    'description'         => 'Render Flukso time series charts.',
    'page callback'       => '_chart_render',
    'page arguments'      => array('electricity', 'day'),
    'access callback'     => TRUE,
    'type'                => MENU_CALLBACK,
  );

  return $items;
} 

function _chart_render() {
  drupal_add_js(CHART_PATH . '/js/highstock.src.js');
  drupal_add_js(CHART_PATH . '/js/flukso.js');

  $output = '<div id="chart" style="height: 500px; width: 600px; margin: 0 0 0 0.6em;"></div>';
  return $output;
}
