<?php

/**
 * sensor.module : sensor administration pages for Flukso
 * Copyright (c) 2011 Bart Van Der Meerssche <bart.vandermeerssche@flukso.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/**
 * hook_perm() callback
 */
function sensor_perm() {
  return array('sensor admin');
}

/**
 * hook_menu() callback 
 */
function sensor_menu() {
  $items = array();

  $items['user/%user_uid_optional/sensors'] = array(
    'title'               => 'Sensors',
    'page callback'       => '_sensor_account',
    'access callback'     => '_sensor_account_access',
    'access arguments'    => array('sensor admin', 1),
    'type'                => MENU_LOCAL_TASK,
    'file'                => 'sensor.admin.inc',
    'weight'              => 3,
  );

  return $items;
}

/**
 * hook_theme() callback
 */
function sensor_theme() {
  return array(
    'sensor_account_list' => array(
      'arguments' => array('items' => NULL),
      'file' => 'sensor.admin.inc',
    ),
  );
}

/**
 * Access callback ensuring the user account tabs are visible only to the
 * owner.
 *
 * @param $permission
 *   Required permission to view the item.
 * @param $account
 *   A user object.
 */
function _sensor_account_access($permission, $account) {
  return ($account->uid == $GLOBALS['user']->uid && user_access($permission));
}

