<?php

/**
 * dash.module : The Flukso dashboard
 * 
 * Copyright (c) 2011 Bart Van Der Meerssche <bart.vandermeerssche@flukso.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

define('DASH_PATH', drupal_get_path('module', 'dash'));
define('DASH_HTML', DASH_PATH . '/tpl/dash.html');

/**
 * hook_menu() callback 
 */
function dash_menu() {
  $items = array();

  $items['dash'] = array(
    'description'         => 'The Flukso dashboard',
    'page callback'       => '_dash_render',
    'access callback'     => TRUE,
    'type'                => MENU_CALLBACK,
  );

  return $items;
} 

function _dash_render() {
  global $user;

  drupal_add_js(DASH_PATH . '/js/underscore-min.js');
  drupal_add_js(DASH_PATH . '/js/backbone-min.js');
  drupal_add_js(DASH_PATH . '/js/backbone-nested-v1.0.3.min.js');
  drupal_add_js(DASH_PATH . '/js/highstock.src.js');
  drupal_add_js(DASH_PATH . '/js/flukso.js');

  drupal_add_js(array('uid' => $user->uid) , 'setting');

  $fd = fopen(DASH_HTML, 'r');
  $body = fread($fd, filesize(DASH_HTML));
  fclose($fd);

  return $body;
}

/**
 * Implementation of hook_form_alter().
 */
function dash_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login') {
    $form['#redirect'] = 'dash';
    $form['name']['#size'] = 20;
    $form['pass']['#size'] = 20;
  }
}


